**Cargamos librerías y datos**

In [25]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as mp

data = pd.read_csv("avistamientos_aerostatos.csv")

**Carga y exploración estructural**

In [ ]:
print("HEAD")
display(data.head(10))
print("TAIL")
display(data.tail())

print("\nComprobación de nulos")
print("=======================")

nulos = []
for s in data:
    if np.any(pd.isna(data[s])):
        nulos.append(data[s].name)

if nulos.__len__() <= 0:
    print("\n -- NO HAY NULOS --\n")
else:
    print("\nColumnas con nulos:")
    for i in nulos:
        print("- ",i)


print("\nTipos de datos")
print("==============")
print(data.dtypes)

print("\n optimicemos memoria convirtiendo los tipo object en distintos tipos primarios o categorizando\n")
print("- ID_Registro -> str")
print("- Pais_Origen -> str")
print("- Tecnologia_Detectada -> str")
print("- Fecha_Avistamiento -> datetime")

data["ID_Registro"] == data["ID_Registro"].astype(str)
data["Pais_Origen"] == data["Pais_Origen"].astype(str)
data["Tecnologia_Detectada"] == data["Tecnologia_Detectada"].astype(str)
data["Fecha_Avistamiento"] == pd.to_datetime(data["Fecha_Avistamiento"])


# print("\n-> Vemos que en la columna Pais_Origen hay un celdas rellenas como Desconocido, hay que vigilar esa columna.")
print("\n-> Hay bastantes filas repetidas, todos los de la cola están también en el inicio del fichero.")
print("Registros con duplicados: ",data.ID_Registro.count())
data = data.drop_duplicates()
print("Registros con duplicados: ",data.ID_Registro.count())

print("\nVemos el resumen estadístico del dataset")
display(data.describe())

HEAD

,ID_Registro,Pais_Origen,Altitud_km,Duracion_Vuelo_h,Velocidad_Viento_kmh,Tecnologia_Detectada,Cercania_Base_Militar_km,Fecha_Avistamiento,Indice_Maniobra
0,REG-1000,EE.UU.,150.00,76.1,82.6,Vigilancia Radar,35.40,2023-02-07,49.38
1,REG-1001,Desconocido,0.50,10.4,94.1,Inteligencia de Señales,103.66,2023-01-31,21.20
2,REG-1002,EE.UU.,25.24,5000.0,39.2,Vigilancia Radar,34.02,2023-01-31,63.00
3,REG-1003,China,29.62,23.0,12.3,Meteorológico,60.58,2023-01-02,96.11
4,REG-1004,Rusia,20.83,26.7,19.0,Meteorológico,246.80,2023-02-06,101.54
5,REG-1005,EE.UU.,20.83,41.5,116.5,Inteligencia de Señales,7.05,2023-01-17,22.01
6,REG-1006,EE.UU.,29.90,19.4,42.5,Vigilancia Radar,16.06,2023-01-08,67.12
7,REG-1007,China,25.84,33.0,94.6,Vigilancia Radar,25.09,2023-01-09,33.77
8,REG-1008,Rusia,19.65,18.0,78.7,Inteligencia de Señales,27.39,2023-02-27,32.41
9,REG-1009,China,24.71,24.7,52.0,Meteorológico,26.47,2023-01-29,69.65

TAIL

,ID_Registro,Pais_Origen,Altitud_km,Duracion_Vuelo_h,Velocidad_Viento_kmh,Tecnologia_Detectada,Cercania_Base_Militar_km,Fecha_Avistamiento,Indice_Maniobra
505,REG-1005,EE.UU.,20.83,41.5,116.5,Inteligencia de Señales,7.05,2023-01-17,22.01
506,REG-1006,EE.UU.,29.90,19.4,42.5,Vigilancia Radar,16.06,2023-01-08,67.12
507,REG-1007,China,25.84,33.0,94.6,Vigilancia Radar,25.09,2023-01-09,33.77
508,REG-1008,Rusia,19.65,18.0,78.7,Inteligencia de Señales,27.39,2023-02-27,32.41
509,REG-1009,China,24.71,24.7,52.0,Meteorológico,26.47,2023-01-29,69.65

Comprobación de nulos
=======================

Columnas con nulos:
-  Altitud_km
-  Tecnologia_Detectada

Tipos de datos
==============
ID_Registro                  object
Pais_Origen                  object
Altitud_km                  float64
Duracion_Vuelo_h            float64
Velocidad_Viento_kmh        float64
Tecnologia_Detectada         object
Cercania_Base_Militar_km    float64
Fecha_Avistamiento           object
Indice_Maniobra             float64
dtype: object

 optimicemos memoria convirtiendo los tipo object en distintos tipos primarios o categorizando

- ID_Registro -> str
- Pais_Origen -> str
- Tecnologia_Detectada -> str
- Fecha_Avistamiento -> datetime

-> Hay bastantes filas repetidas, todos los de la cola están también en el inicio del fichero.
Registros con duplicados:  510
Registros con duplicados:  500

Vemos el resumen estadístico del dataset

,Altitud_km,Duracion_Vuelo_h,Velocidad_Viento_kmh,Cercania_Base_Militar_km,Indice_Maniobra
count,460.000000,500.000000,500.00000,500.000000,500.000000
mean,22.253609,58.833600,65.54480,50.472620,54.394560
std,7.756068,223.929538,31.49662,50.565344,23.241086
min,0.500000,1.500000,10.40000,0.010000,3.480000
25%,18.482500,24.700000,38.35000,15.812500,34.905000
50%,22.090000,41.650000,66.95000,33.500000,53.790000
75%,25.232500,63.700000,93.12500,70.627500,72.625000
max,150.000000,5000.000000,119.80000,306.440000,116.620000