In [ ]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("./dist_renta_hogares_limpio.csv")

Comprobemos si los datos sirven para análisis

In [31]:
print("Observamos esta columna que es clasificable en 3 categorías de umbral de probreza\n")
con_valor = data.Total > 0
con_valor = data[con_valor]
chorizo = data["Distribución de la renta por unidad de consumo"]
print(chorizo.value_counts())

# Cambiamos el nombre de una columna para trabajar mejor
data.rename(columns={"Distribución de la renta por unidad de consumo":"Distribucion_Renta"},inplace=True)


print("\nCreamos una nueva columna para clasificar con un código más corto los 3 umbrales de renta y hacemos recuento para ver que concuerda con la columna que categoriza\n")
# u5 = 5.000 - u7 = 7.500 - u10 = 10.000 
data["umbral_pobreza"] = np.where(data.Distribucion_Renta.str.contains("10.000"),"u10",np.where(data.Distribucion_Renta.str.contains("7.500"),"u7","u5") )
data["umbral_pobreza"] = data["umbral_pobreza"].astype("category")

print(data.umbral_pobreza.value_counts())

print("\n\n")

print("Como vemos, el periodo habla siempre del 1 de enero del año, por lo que simplificaremos el dato a solo el año\n")

data.Periodo = pd.to_datetime(data.Periodo)
data.Periodo = data.Periodo.dt.strftime("%Y")

print("\nCorregimos la columna Codigo_Posta, que vienen todas con el mísmo código \n")
Cod_Postal = np.where(data.Secciones != "No",data.Secciones.str[0:5],
                      np.where(data.Distritos != "No", data.Distritos.str[:5], data.Municipios.str[:5]))
data.Cod_Postal = Cod_Postal

print("\n\n")
display(data)

Observamos esta columna que es clasificable en 3 categorías de umbral de probreza

Distribución de la renta por unidad de consumo
Población con ingresos por unidad de consumo por debajo de 5.000 Euros     26244
Población con ingresos por unidad de consumo por debajo de 7.500 Euros     26244
Población con ingresos por unidad de consumo por debajo de 10.000 Euros    26244
Name: count, dtype: int64

Creamos una nueva columna para clasificar con un código más corto los 3 umbrales de renta y hacemos recuento para ver que concuerda con la columna que categoriza

umbral_pobreza
u10    26244
u5     26244
u7     26244
Name: count, dtype: int64



Como vemos, el periodo habla siempre del 1 de enero del año, por lo que simplificaremos el dato a solo el año


Corregimos la columna Codigo_Posta, que vienen todas con el mísmo código

,Municipios,Distritos,Secciones,Sexo,Nacionalidad,Distribucion_Renta,Periodo,Total,Cod_Postal,Porcentaje,umbral_pobreza
0,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2015,0.0,32001,Bajo,u5
1,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2015,0.0,32001,Bajo,u7
2,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2015,0.0,32001,Bajo,u10
3,32001 Allariz,No,No,Total,Extranjera,Población con ingresos por unidad de consumo p...,2015,0.0,32001,Bajo,u5
4,32001 Allariz,No,No,Total,Extranjera,Población con ingresos por unidad de consumo p...,2015,0.0,32001,Bajo,u7
...,...,...,...,...,...,...,...,...,...,...,...
78727,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Española,Población con ingresos por unidad de consumo p...,2023,0.0,32092,Bajo,u7
78728,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Española,Población con ingresos por unidad de consumo p...,2023,0.0,32092,Bajo,u10
78729,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2023,0.0,32092,Bajo,u5
78730,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2023,0.0,32092,Bajo,u7
78731,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2023,0.0,32092,Bajo,u10

**Optimizamos los tipos de datos**

In [32]:
data['Municipios'] = data['Municipios'].astype('category')
data['Distritos'] = data['Distritos'].astype('category')
data['Secciones'] = data['Secciones'].astype('category')
data['Sexo'] = data['Sexo'].astype('category')
data['Nacionalidad'] = data['Nacionalidad'].astype('category')
data['Periodo'] = data['Periodo'].astype('category')
data['Cod_Postal'] = data['Cod_Postal'].astype('category')

display(data.dtypes)

Municipios            category
Distritos             category
Secciones             category
Sexo                  category
Nacionalidad          category
Distribucion_Renta      object
Periodo               category
Total                  float64
Cod_Postal            category
Porcentaje              object
umbral_pobreza        category
dtype: object

## Perfilado estadístico

In [42]:
display(data.describe().round(2))
print(data.Cod_Postal.value_counts().quantile(0.75))

# for i in data:
#     print(i)
#     serie_aux = [data[i].count(),
#     str(data[i].mean()),
#     str(data[i].std()),  
#     str(data[i].min()),    
#     str(data[i].quantile(0.25)),
#     str(data[i].quantile(0.50)),    
#     str(data[i].quantile(0.75)),    
#     str(data[i].max())]

          Total
count  78732.00
mean       0.78
std        5.83
min        0.00
25%        0.00
50%        0.00
75%        0.00
max       80.80

810.0

**Coluna Total**  
La columna Total sería el porcentaje de personas que cumplen los requisitos de las columnas descriptivas. En este caso no se discrimina si hay o no personas que cumplan los requisitos para aparecer en la estadística, por lo que la mayoría de las celdas están a 0.0
Aún así es importante, ya que necesitamos ver la predicción de crecimiento o decrecimiento de la población en los distintos umbrales de renta.